# Generated by Django 2.2.7 on 2019-12-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('brandIcon', models.ImageField(blank=True, null=True, upload_to='media/brand-icons')),
            ],
        ),
        migrations.CreateModel(
            name='ModelNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('modelImage', models.ImageField(blank=True, default=None, upload_to='media/model-image')),
                ('brandID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.BrandName')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('modelNumberId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone.ModelNumber')),
            ],
        ),
    ]
