# Generated by Django 2.2.7 on 2019-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandname',
            name='brandIcon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media/brand-icons'),
        ),
    ]
