# Generated by Django 2.2.7 on 2019-12-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelnumber',
            name='modelImage',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
