# Generated by Django 2.2.7 on 2019-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0002_modelnumber_modelimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelnumber',
            name='modelImage',
            field=models.ImageField(blank=True, default=None, upload_to='media/'),
        ),
    ]
