# Generated by Django 2.2.7 on 2020-01-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20191221_1732'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brandname',
            table='BrandName',
        ),
        migrations.AlterModelTable(
            name='modelnumber',
            table='ModelNumber',
        ),
        migrations.AlterModelTable(
            name='variant',
            table='Varient',
        ),
    ]
