# Generated by Django 2.2.7 on 2019-12-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20191214_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandname',
            name='brandIcon',
            field=models.ImageField(blank=True, default=None, upload_to='brand-icons/'),
        ),
        migrations.AlterField(
            model_name='modelnumber',
            name='modelImage',
            field=models.ImageField(blank=True, default=None, upload_to='model-image/'),
        ),
    ]
