# Generated by Django 2.2.7 on 2019-12-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0003_auto_20191203_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelnumber',
            old_name='modelName',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='veriantName',
            new_name='name',
        ),
    ]
