# Generated by Django 2.2.7 on 2020-01-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0004_auto_20200106_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='billAboveThreeMonth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='billBelowThreeMonth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hasBox',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hasCharger',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='hasHeadPhone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='isExcellent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='isFair',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='isNew',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='no_issue_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
